name: my first workflow

on: [push, workflow_dispatch]

jobs:
  run-one-command:
    runs-on: ubuntu-latest
    steps:
      - name: List All File
        run: ls -a
      - name: Print Working directory
        run: pwd
      - name: Create js File
        run: echo 'console.log("hello world")' > app.js
      - name: List All File
        run: ls -a
      - name: Run Node js File
        run: node app.js
      - name: System name
        run: uname -a
      - name: OS verison
        run: cat /etc/os-release
      - name: cpu Info
        run: free -h
        
  my-second-job:
    runs-on: ubuntu-latest
    needs: run-one-command
    steps:
      - name: Print node js version
        run: node -v
      - name: Print all files
        run: ls -a

   
